# Use the official Node.js image as the base image
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# opy the package.json and package-lock.json
COPY package*.json ./

# Install dependencies (including dev dependencies)
RUN npm install

# Copy the rest of your application code
COPY . .

# Expose the port on which Next.js app runs (e.g., 3000)
EXPOSE 3000

# Use nodemon to start the application in development mode
CMD ["npm", "run", "dev"]